name: hlivy
version: '0.1.0.0'
author: Daniel Donohue
maintainer: ddonohue@earnestresearch.com
copyright: 2018 Earnest Research
license: BSD3
homepage: https://github.com/EarnestResearch/hlivy

dependencies:
  - aeson
  - base
  - bytestring
  - http-client
  - http-conduit
  - http-types
  - lens
  - mtl
  - text
  - transformers
  - unordered-containers

default-extensions:
  - OverloadedStrings

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -fno-warn-type-defaults
